on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: yarn && yarn build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/
    - name: List files in current directory
      run: ls
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: List files in current directory
        run: ls
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Deploy to Aliyun ECS
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          # Private key part of an SSH key pair
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.HOST }}
          # Remote user
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: "dist/*"
          TARGET: "/site"